name: timefolio # 앱 이름 변경 # import 'package:timefolio' 함께 변경 필요;
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^12.1.3
  provider: ^6.1.2
  webview_flutter: ^4.8.0
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.1.0
  permission_handler: ^11.3.0
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  package_info_plus: ^8.2.1
  smooth_page_indicator: ^1.1.0
  flutter_slidable: ^3.0.1

  # 로컬 저장소 사용 시
  shared_preferences: ^2.2.3
  path_provider: ^2.1.2
  uuid: ^4.2.2

  # Supabase 사용 시
  supabase_flutter: ^2.3.4

  # # 공유기능 사용 시
  # share_plus: ^7.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env
